# Generated by Django 2.2.5 on 2022-01-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mood', models.CharField(max_length=1)),
                ('reported_on', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=255)),
                ('site', models.CharField(max_length=255)),
            ],
        ),
    ]
